[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
restartPolicyType = "always"

[[services]]
name = "xightmd-frontend"
source = "xightmd"
[services.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"

[[services]]
name = "xightmd-backend"
source = "backend"
[services.variables]
PYTHONPATH = "/app"
PORT = "8000"