'use client';

import { AnalysisResult } from '@/types';
import { useState } from 'react';

interface ReportDisplayProps {
  analysis: AnalysisResult | null;
  isLoading: boolean;
}

export default function ReportDisplay({ analysis, isLoading }: ReportDisplayProps) {
  const [selectedFindings, setSelectedFindings] = useState<string[]>([]);
  const [radiologistNotes, setRadiologistNotes] = useState('');
  const [showValidation, setShowValidation] = useState(false);

  // Function to download PDF report
  const handleDownloadPDF = () => {
    if (!analysis || !analysis.pdf_data) {
      // Fallback to text download if no PDF available
      handleDownloadReport();
      return;
    }
    
    try {
      // Decode base64 PDF data
      const binaryString = atob(analysis.pdf_data);
      const bytes = new Uint8Array(binaryString.length);
      for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
      
      // Create and download PDF
      const blob = new Blob([bytes], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `xray_analysis_${analysis.id}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading PDF:', error);
      alert('Error downloading PDF. Downloading text report instead.');
      handleDownloadReport();
    }
  };

  // Function to download text report (fallback)
  const handleDownloadReport = () => {
    if (!analysis) return;
    
    const reportContent = `
CHEST X-RAY ANALYSIS REPORT
Generated: ${new Date(analysis.timestamp).toLocaleString()}
Analysis ID: ${analysis.id}
Priority Level: ${analysis.urgency >= 4 ? 'High Priority' : analysis.urgency >= 3 ? 'Medium Priority' : 'Normal'}
Confidence: ${(analysis.confidence * 100).toFixed(1)}%

INDICATION:
${analysis.report.indication}

COMPARISON:
${analysis.report.comparison}

FINDINGS:
${analysis.report.findings}

IMPRESSION:
${analysis.report.impression}

KEY FINDINGS:
${analysis.findings.map(finding => `• ${finding}`).join('\n')}

${selectedFindings.length > 0 ? `
RADIOLOGIST VALIDATION:
Confirmed Findings: ${selectedFindings.join(', ')}
` : ''}

${radiologistNotes ? `
ADDITIONAL NOTES:
${radiologistNotes}
` : ''}

---
Generated by XightMD AI-Powered Chest X-ray Analysis System
IMPORTANT: This report is for research and educational purposes only.
Always consult qualified healthcare professionals for medical diagnosis.
    `.trim();
    
    // Create and download text file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `xray_analysis_${analysis.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Function to share results (copy to clipboard)
  const handleShareResults = async () => {
    if (!analysis) return;
    
    const shareText = `XightMD Analysis Results:
• Priority: ${analysis.urgency >= 4 ? 'High' : analysis.urgency >= 3 ? 'Medium' : 'Normal'}
• Confidence: ${(analysis.confidence * 100).toFixed(1)}%
• Key Findings: ${analysis.findings.slice(0, 3).join(', ')}
• Impression: ${analysis.report.impression}
• Analysis ID: ${analysis.id}`;

    try {
      await navigator.clipboard.writeText(shareText);
      alert('Results copied to clipboard!');
    } catch (err) {
      console.error('Failed to copy:', err);
      alert('Failed to copy results to clipboard');
    }
  };

  // Handle radiologist validation
  const handleFindingToggle = (finding: string) => {
    setSelectedFindings(prev => 
      prev.includes(finding) 
        ? prev.filter(f => f !== finding)
        : [...prev, finding]
    );
  };

  if (isLoading) {
    return (
      <div className="bg-white rounded-xl shadow-lg p-6">
        <h2 className="text-xl font-bold text-gray-900 mb-6">Analysis Results</h2>
        <div className="space-y-4">
          <div className="animate-pulse">
            <div className="h-4 bg-gray-200 rounded w-3/4 mb-2"></div>
            <div className="h-4 bg-gray-200 rounded w-1/2"></div>
          </div>
          <div className="animate-pulse">
            <div className="h-20 bg-gray-200 rounded"></div>
          </div>
          <div className="animate-pulse">
            <div className="h-4 bg-gray-200 rounded w-2/3 mb-2"></div>
            <div className="h-4 bg-gray-200 rounded w-1/3"></div>
          </div>
        </div>
      </div>
    );
  }

  if (!analysis) {
    return (
      <div className="bg-white rounded-xl shadow-lg p-6">
        <h2 className="text-xl font-bold text-gray-900 mb-6">Analysis Results</h2>
        <div className="text-center py-12">
          <div className="w-16 h-16 mx-auto bg-gray-100 rounded-full flex items-center justify-center mb-4">
            <svg className="w-8 h-8 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <p className="text-gray-500 text-lg">Upload a chest X-ray to see AI analysis results</p>
          <p className="text-gray-400 text-sm mt-2">Our AI agents will provide detailed findings and impressions</p>
        </div>
      </div>
    );
  }

  const getUrgencyColor = (urgency: number) => {
    if (urgency >= 4) return 'bg-red-100 text-red-800 border-red-200';
    if (urgency >= 3) return 'bg-yellow-100 text-yellow-800 border-yellow-200';
    return 'bg-green-100 text-green-800 border-green-200';
  };

  const getUrgencyLabel = (urgency: number) => {
    if (urgency >= 4) return 'High Priority';
    if (urgency >= 3) return 'Medium Priority';
    return 'Normal';
  };

  return (
    <div className="bg-white rounded-xl shadow-lg p-6 space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold text-gray-900">Analysis Results</h2>
        <div className="text-sm text-gray-500">
          {new Date(analysis.timestamp).toLocaleString()}
        </div>
      </div>

      {/* Urgency and Confidence Indicators */}
      <div className="grid grid-cols-2 gap-4">
        <div className={`p-3 rounded-lg border ${getUrgencyColor(analysis.urgency)}`}>
          <div className="text-sm font-medium">Priority Level</div>
          <div className="text-lg font-bold">{getUrgencyLabel(analysis.urgency)}</div>
        </div>
        <div className="p-3 rounded-lg border bg-blue-50 text-blue-800 border-blue-200">
          <div className="text-sm font-medium">Confidence</div>
          <div className="text-lg font-bold">{(analysis.confidence * 100).toFixed(1)}%</div>
        </div>
      </div>

      {/* AI Findings with Validation */}
      <div className="bg-gray-50 rounded-lg p-4">
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-semibold text-gray-900">AI Detected Findings</h3>
          <button
            onClick={() => setShowValidation(!showValidation)}
            className="text-sm text-blue-600 hover:text-blue-700 font-medium"
          >
            {showValidation ? 'Hide Validation' : 'Validate Findings'}
          </button>
        </div>
        
        <div className="space-y-2">
          {analysis.findings.map((finding, index) => (
            <div key={index} className="flex items-start space-x-2">
              {showValidation ? (
                <button
                  onClick={() => handleFindingToggle(finding)}
                  className={`mt-1 w-4 h-4 rounded border-2 flex items-center justify-center transition-colors ${
                    selectedFindings.includes(finding)
                      ? 'bg-green-500 border-green-500 text-white'
                      : 'border-gray-300 hover:border-green-400'
                  }`}
                >
                  {selectedFindings.includes(finding) && (
                    <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                  )}
                </button>
              ) : (
                <div className="w-2 h-2 bg-blue-500 rounded-full mt-2 flex-shrink-0"></div>
              )}
              <span className={`text-gray-700 text-sm ${selectedFindings.includes(finding) ? 'font-medium text-green-700' : ''}`}>
                {finding}
              </span>
            </div>
          ))}
        </div>

        {showValidation && (
          <div className="mt-4 space-y-3">
            <div>
              <label htmlFor="radiologist-notes" className="block text-sm font-medium text-gray-700 mb-1">
                Additional Notes (Radiologist Input)
              </label>
              <textarea
                id="radiologist-notes"
                rows={3}
                value={radiologistNotes}
                onChange={(e) => setRadiologistNotes(e.target.value)}
                placeholder="Add your professional observations or corrections..."
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm"
              />
            </div>
            {selectedFindings.length > 0 && (
              <div className="bg-green-50 border border-green-200 rounded-lg p-3">
                <p className="text-sm text-green-800 font-medium">
                  ✅ Validated Findings: {selectedFindings.length} of {analysis.findings.length}
                </p>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Detailed Report */}
      <div className="space-y-4">
        <h3 className="font-semibold text-gray-900">Radiology Report</h3>
        
        <div className="space-y-4">
          <div className="border-l-4 border-blue-500 pl-4 py-2 bg-blue-50">
            <h4 className="font-medium text-blue-900 mb-1">INDICATION</h4>
            <p className="text-blue-800 text-sm">{analysis.report.indication}</p>
          </div>

          <div className="border-l-4 border-green-500 pl-4 py-2 bg-green-50">
            <h4 className="font-medium text-green-900 mb-1">COMPARISON</h4>
            <p className="text-green-800 text-sm">{analysis.report.comparison}</p>
          </div>

          <div className="border-l-4 border-purple-500 pl-4 py-2 bg-purple-50">
            <h4 className="font-medium text-purple-900 mb-1">FINDINGS</h4>
            <p className="text-purple-800 text-sm leading-relaxed">{analysis.report.findings}</p>
          </div>

          <div className="border-l-4 border-orange-500 pl-4 py-2 bg-orange-50">
            <h4 className="font-medium text-orange-900 mb-1">IMPRESSION</h4>
            <p className="text-orange-800 text-sm font-medium">{analysis.report.impression}</p>
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex space-x-3 pt-4 border-t">
        <button 
          onClick={handleDownloadPDF}
          className="flex-1 bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium flex items-center justify-center space-x-2"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <span>Download {analysis.pdf_data ? 'PDF' : 'Report'}</span>
        </button>
        <button 
          onClick={handleShareResults}
          className="flex-1 border border-gray-300 text-gray-700 py-2 px-4 rounded-lg hover:bg-gray-50 transition-colors text-sm font-medium flex items-center justify-center space-x-2"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z" />
          </svg>
          <span>Share Results</span>
        </button>
      </div>

      {/* Validation Summary */}
      {showValidation && selectedFindings.length > 0 && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
          <h4 className="font-medium text-green-900 mb-2">Validation Summary</h4>
          <p className="text-sm text-green-800">
            <strong>Confirmed Findings:</strong> {selectedFindings.join(', ')}
          </p>
          {radiologistNotes && (
            <p className="text-sm text-green-800 mt-2">
              <strong>Notes:</strong> {radiologistNotes}
            </p>
          )}
        </div>
      )}

      {/* Analysis ID and Disclaimer */}
      <div className="text-xs text-gray-400 text-center pt-2 border-t space-y-1">
        <p>Analysis ID: {analysis.id}</p>
        <p className="text-red-600 font-medium">
          ⚠️ For research and educational purposes only. Not for clinical diagnosis.
        </p>
      </div>
    </div>
  );
}